package com.web.enums;

public enum ConfigProperties {
    URL,
    BROWSE,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    FAILEDTESTRETRYCOUNT,
    RUNMODE



}
